apiVersion: apps/v1 #version of the Kubernetes API you're using to create this object
kind: Deployment  #What kind of object you want to create
metadata: #deployment name, helps uniquely identify the object
   name: deliveryagentms

spec:  
  selector:
    matchLabels:
      app: deliveryagentms


  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: deliveryagentms
    spec:   #What state you desire for the object

      containers:
      - name: deliveryagentms #container name
        image: 'jasminmishra/electronicstore:v1' #image name
        ports:
        - containerPort: 4441 # demo runs on port 8484