apiVersion: v1
kind: Service #What kind of object you want to create
metadata: #service name,Data that helps uniquely identify the object
  name: deliveryagentms
spec: #What state you desire for the object
  selector:
    app: deliveryagentms
  ports:
    - port: 4441  #port at which service is internally available
      targetPort: 4441 #port of container
      
      name: deliveryagentms
  type: LoadBalancer